version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-nightly
      - test-stable

jobs:
  test-nightly:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;

  test-stable:
    docker:
      - image: circleci/rust:1.35
    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;

