version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-stable
      - test-nightly
      - coverage

jobs:
  test-stable:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;
  test-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: coverage
          command: docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin sh -c 'cargo tarpaulin --exclude-files "src/bin/*.rs" --out Xml'
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)

