version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-stable
      - test-nightly

jobs:
  test-stable:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;
      - run:
          name: coverage
          command: |
            cargo install cargo-tarpaulin
            cargo tarpaulin --out Xml
            bash <(curl -s https://codecov.io/bash)

  test-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: version
          command: rustc --version
      - run:
          name: test
          command: cargo test
      - run:
          name: bin
          command: find ./test/*.sh -exec {} \;

